apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-q2ub
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-q2ub
    app.kubernetes.io/part-of: cin4s-839-0068-app
  name: devfile-sample-q2ub
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-q2ub
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-q2ub
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0068-tenant/cin4s-839-0068-app/devfile-sample-q2ub@sha256:4b96510c5b0eb5fe347e9e022255d948a0273311dea44569d16f61142cf36f1d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
